//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * ähnelt.
        /// </summary>
        public static string AuthAllServer {
            get {
                return ResourceManager.GetString("AuthAllServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zertifikat ähnelt.
        /// </summary>
        public static string AuthCERT {
            get {
                return ResourceManager.GetString("AuthCERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CERT ähnelt.
        /// </summary>
        public static string AuthModeCERT {
            get {
                return ResourceManager.GetString("AuthModeCERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PWD ähnelt.
        /// </summary>
        public static string AuthModePWD {
            get {
                return ResourceManager.GetString("AuthModePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kein Modus gewählt! ähnelt.
        /// </summary>
        public static string AuthNoMode {
            get {
                return ResourceManager.GetString("AuthNoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ******* ähnelt.
        /// </summary>
        public static string AuthPassword {
            get {
                return ResourceManager.GetString("AuthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22 ähnelt.
        /// </summary>
        public static string AuthPort {
            get {
                return ResourceManager.GetString("AuthPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer/Passwort ähnelt.
        /// </summary>
        public static string AuthPWD {
            get {
                return ResourceManager.GetString("AuthPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * ähnelt.
        /// </summary>
        public static string AuthServer {
            get {
                return ResourceManager.GetString("AuthServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die toolbox ähnelt.
        /// </summary>
        public static string AuthUsername {
            get {
                return ResourceManager.GetString("AuthUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate/ ähnelt.
        /// </summary>
        public static string CertificateDirPath {
            get {
                return ResourceManager.GetString("CertificateDirPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zertifikate|*.crt;*.pem;*.cert;*.ssh|Alle Dateien (*.*)|*.* ähnelt.
        /// </summary>
        public static string CertificateFileFilter {
            get {
                return ResourceManager.GetString("CertificateFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim hochladen der Toolbox auf den Server ähnelt.
        /// </summary>
        public static string ConnectionBashFail {
            get {
                return ResourceManager.GetString("ConnectionBashFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bash Toolbox fehler ähnelt.
        /// </summary>
        public static string ConnectionBashTool {
            get {
                return ResourceManager.GetString("ConnectionBashTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung hergestellt ähnelt.
        /// </summary>
        public static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinung fehlgeschlagen ähnelt.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung zu Server fehlgeschlagen! ähnelt.
        /// </summary>
        public static string ConnectionFault {
            get {
                return ResourceManager.GetString("ConnectionFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinden... ähnelt.
        /// </summary>
        public static string ConnectionRun {
            get {
                return ResourceManager.GetString("ConnectionRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (c) 2017 elmProjekt, Alle Rechte vorbehalten ähnelt.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string EMPTY {
            get {
                return ResourceManager.GetString("EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweis ähnelt.
        /// </summary>
        public static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ipaddress ähnelt.
        /// </summary>
        public static string keyIPAddress {
            get {
                return ResourceManager.GetString("keyIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die language ähnelt.
        /// </summary>
        public static string keyLanguage {
            get {
                return ResourceManager.GetString("keyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mode ähnelt.
        /// </summary>
        public static string keyMode {
            get {
                return ResourceManager.GetString("keyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die none ähnelt.
        /// </summary>
        public static string keyNone {
            get {
                return ResourceManager.GetString("keyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die password ähnelt.
        /// </summary>
        public static string keyPassword {
            get {
                return ResourceManager.GetString("keyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die port ähnelt.
        /// </summary>
        public static string keyPort {
            get {
                return ResourceManager.GetString("keyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die server ähnelt.
        /// </summary>
        public static string keyServer {
            get {
                return ResourceManager.GetString("keyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die username ähnelt.
        /// </summary>
        public static string keyUsername {
            get {
                return ResourceManager.GetString("keyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/sunriax/elm-project ähnelt.
        /// </summary>
        public static string LinkGithub {
            get {
                return ResourceManager.GetString("LinkGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http:// ähnelt.
        /// </summary>
        public static string Linkhttp {
            get {
                return ResourceManager.GetString("Linkhttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https:// ähnelt.
        /// </summary>
        public static string Linkhttps {
            get {
                return ResourceManager.GetString("Linkhttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Debug Modus ist eingeschalten! ähnelt.
        /// </summary>
        public static string MsgDebugMode {
            get {
                return ResourceManager.GetString("MsgDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dialog wirklich schließen? ähnelt.
        /// </summary>
        public static string MsgDialogExit {
            get {
                return ResourceManager.GetString("MsgDialogExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler in der IP-Adresse ähnelt.
        /// </summary>
        public static string MsgIPFault {
            get {
                return ResourceManager.GetString("MsgIPFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingestelltes Sprachpaket konnte nicht gealden werden! ähnelt.
        /// </summary>
        public static string MsgLanguageNotFound {
            get {
                return ResourceManager.GetString("MsgLanguageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache erfolgreich eingestellt, zum übernehmen ist ein Neustart der Toolbox erforderlich! ähnelt.
        /// </summary>
        public static string MsgLanguageSetup {
            get {
                return ResourceManager.GetString("MsgLanguageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Objekt markiert! ähnelt.
        /// </summary>
        public static string MsgObjectMark {
            get {
                return ResourceManager.GetString("MsgObjectMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm wirklich beenden? ähnelt.
        /// </summary>
        public static string MsgProgramExit {
            get {
                return ResourceManager.GetString("MsgProgramExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten entsprechen den Standardeingabedaten, wirklich fortsetzten? ähnelt.
        /// </summary>
        public static string MsgSameData {
            get {
                return ResourceManager.GetString("MsgSameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP: 192.168.0.1; HOST: server.host; DOMAIN: ssh.sunriax.at; ähnelt.
        /// </summary>
        public static string MsgServerHelp {
            get {
                return ResourceManager.GetString("MsgServerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox wurde auf Server hochgeladen ähnelt.
        /// </summary>
        public static string MsgToolboxUpload {
            get {
                return ResourceManager.GetString("MsgToolboxUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Version  ähnelt.
        /// </summary>
        public static string MsgToolboxVersion {
            get {
                return ResourceManager.GetString("MsgToolboxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die n.A. ähnelt.
        /// </summary>
        public static string NotAvileable {
            get {
                return ResourceManager.GetString("NotAvileable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nicht gefunden! ähnelt.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Wählen ähnelt.
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1024@Fynn_20170403 ähnelt.
        /// </summary>
        public static string ProgramBuild {
            get {
                return ResourceManager.GetString("ProgramBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die elmProject ähnelt.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die V1.0A ähnelt.
        /// </summary>
        public static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/sshnet/ ähnelt.
        /// </summary>
        public static string RenciSSHLink {
            get {
                return ResourceManager.GetString("RenciSSHLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SSH Klasse basiert auf SSH.NET ähnelt.
        /// </summary>
        public static string RenciSSHText {
            get {
                return ResourceManager.GetString("RenciSSHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die / ähnelt.
        /// </summary>
        public static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ***************** ähnelt.
        /// </summary>
        public static string SpacerPassword {
            get {
                return ResourceManager.GetString("SpacerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de-AT ähnelt.
        /// </summary>
        public static string SpeakdeAT {
            get {
                return ResourceManager.GetString("SpeakdeAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-GB ähnelt.
        /// </summary>
        public static string SpeakenGB {
            get {
                return ResourceManager.GetString("SpeakenGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die es-ES ähnelt.
        /// </summary>
        public static string SpeakesES {
            get {
                return ResourceManager.GetString("SpeakesES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterbarer Linux Mikrocomputer ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zertifikat ähnelt.
        /// </summary>
        public static string ValueCertificate {
            get {
                return ResourceManager.GetString("ValueCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ******** ähnelt.
        /// </summary>
        public static string ValuePassword {
            get {
                return ResourceManager.GetString("ValuePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22 ähnelt.
        /// </summary>
        public static string ValuePort {
            get {
                return ResourceManager.GetString("ValuePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        public static string ValueServer {
            get {
                return ResourceManager.GetString("ValueServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer ähnelt.
        /// </summary>
        public static string ValueUsername {
            get {
                return ResourceManager.GetString("ValueUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
